### PR TITLE
Implement split_and_recombine_text for longer prompt generations

### PR DESCRIPTION
**Pull request by JonSingleton**
You may have a preference for how this is done, I just borrowed the split_and_recombine_text function from tortoise, placed it in the utils folder and imported it at the top then worked it into your generate_audio function.

Also set launch to use the port being generated in the while loop above it.

### CODE REVIEW

**Comment by JarodMica** [comment]
Appreciate the improvement, I'll look through it and test it sometime soon! 👍

**Comment by code-switched** [comment]
I've changed my local `webui.py` and added `splitcombine.py` to match this pull request and can confirm it works well. I also removed the `print(f'model:{model}')` statement so I could follow what was going on in the CLI.

I had two thoughts while using this...
- Lowering the `desired_length` and `max_length` could lead to better generations for my use case.
- Seeing those two variables as options to increase or decrease in the UI would be cool.

Could also do `gr.TextArea` instead of `gr.Textbox` if longer prompts work with this update.

I have not tried anything longer than a paragraph yet but this shows a lot of promise.

**Comment by JonSingleton** [comment]
I sloppily implemented some code from ebook2audiobookSTYLETTS2 and added a new tab "Generate Audiobook" in my fork. It's set to use the generation settings from the generation tab to narrate whatever ebook you input to it. 
It's far from perfect and there's some issues I don't really care to track down and the code needs a lot of cleanup, but with low diffusion steps it's managed to convert an epub of How To Win Friends and Influence People in a little under 30 minutes - my point here is it's utilizing the above pull request to generate full-length audiobooks so it seems reasonably functional for most use-cases.

**Comment by JarodMica** [comment]
Merge looks good.  I will be moving the recombine and split into the styletts2 submodule instead, but idk how the process would work to have you do this in this repo so I'm just gonna tidy it up after the fact

**Comment by JonSingleton** [comment]
🤷‍♂️ no clue - I'll just check out what you did afterwards and make those changes to mine later on.

**Comment by JarodMica** [comment]
It would require you to PR for both repos I believe.  Easier if I just did it which is implemented here https://github.com/JarodMica/StyleTTS-WebUI/commit/69e31d8dddc6e0809491e314fad8c2571be4049a

**Pull request merged**
